# Generated by Django 5.1.5 on 2025-02-05 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_register_licence_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='licence_no',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
