# Generated by Django 5.1.5 on 2025-02-13 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_reset'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
