# Generated by Django 5.1.5 on 2025-02-19 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0007_alter_reset_user_policy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='policy',
            old_name='created_at',
            new_name='created_on',
        ),
    ]
