# Generated by Django 5.1.5 on 2025-02-19 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0008_rename_created_at_policy_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='cover_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
