# Generated by Django 5.1.5 on 2025-02-25 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0009_policy_cover_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='no_months',
            field=models.CharField(default=20, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='policy',
            name='total_amnt',
            field=models.CharField(default=100000, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='policy',
            name='cover_amount',
            field=models.CharField(default=500, max_length=255),
            preserve_default=False,
        ),
    ]
