# Generated by Django 5.1.5 on 2025-02-25 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0010_policy_no_months_policy_total_amnt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='policy_images/'),
        ),
    ]
