# Generated by Django 5.1.5 on 2025-02-25 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0011_policy_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMedicalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('other_details', models.TextField(blank=True, null=True)),
                ('medical_condition', models.TextField(blank=True, null=True)),
                ('health_reports', models.FileField(blank=True, null=True, upload_to='health_reports/')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_info', to='userapp.policy')),
            ],
        ),
    ]
