# Generated by Django 5.1.5 on 2025-02-25 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0012_usermedicalinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermedicalinfo',
            name='other_details',
        ),
        migrations.AddField(
            model_name='usermedicalinfo',
            name='address',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermedicalinfo',
            name='age',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermedicalinfo',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermedicalinfo',
            name='phone_number',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermedicalinfo',
            name='pincode',
            field=models.CharField(default='', max_length=6),
            preserve_default=False,
        ),
    ]
