# Generated by Django 5.1.5 on 2025-02-26 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0013_remove_usermedicalinfo_other_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='provider_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
